### ISSUE TITLE
DROP IF EXISTS

### ISSUE THREAD

**Issue by marek-witkowski** [adambernas/Technical_Catalog_Management#10]
Jeśli nie potrzebujesz kompatybilności wstecznej to od SQL 2016 wprowadzono coś takiego:

DROP [object] IF EXISTS [object_name]

np.

DROP DATABASE IF EXISTS baza_danych.

i można sobie uprościć :)

**Comment by adambernas** [comment]
Znam te polecenia ale działam na wersji SQL Server 2014 a w niej to jeszcze nie było wprowadzone :)
