### ISSUE TITLE
Brak polskich liter w komentarzach

### ISSUE THREAD

**Issue by marek-witkowski** [adambernas/Technical_Catalog_Management#9]
Brak polskich liter w komentarzach - pewnie coś się w kodowaniu pliki rozjechało.

**Comment by marek-witkowski** [comment]
Pliki z raportami: 2 i 3

**Comment by adambernas** [comment]
Naprawione. Przy zapisywaniu pliku zmieniłem metodę kodowania na unicode UTF-8 i pomogło ale co ciekawe pozostałe pliki są kodowane po staremu a polskie znaki widać
